mqtt:
  host: host.docker.internal
  port: 1883
  # user: mosquitto
  # password: 1234
cameras:
  webcam:
    rtmp:
      enabled: False
    ffmpeg:
      inputs:
        - path: /dev/video0
          input_args: -f v4l2 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
          roles:
            - detect
            # - rtmp
            - record
      output_args:
        # rtmp: -vf transpose=2,transpose=2 -c:v libx264 -preset ultrafast -tune zerolatency -b:v 600k -f flv
        # record: -vf transpose=2,transpose=2 -c:v libx264 -preset ultrafast -tune zerolatency -b:v 600k -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -an
        record: -f rawvideo -pix_fmt yuv420p
        detect: -f rawvideo -pix_fmt yuv420p
      # output_args:
      #   detect: -f rawvideo -pix_fmt yuv420p
    detect:
      width: 1280
      height: 720
      fps: 5
      max_disappeared: 10
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: False
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: False
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: height to resize the snapshot to (default: shown below)
      height: 720
      # Optional: jpeg encode quality (default: shown below)
      quality: 90
snapshots: 
  enabled: True
  timestamp: False
  bounding_box: False
      # bounding_box: True
      # crop:
      #   False

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - cat
  # Optional: mask to prevent all object types from being detected in certain areas (default: no mask)
  # Checks based on the bottom center of the bounding box of the object.
  # NOTE: This mask is COMBINED with the object type specific mask below
  # mask: 0,0,1000,0,1000,200,0,200
  # Optional: filters to reduce false positives for specific object types
  # filters:
  #   cat:
  #     # Optional: minimum width*height of the bounding box for the detected object (default: 0)
  #     min_area: 5000
  #     # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
  #     max_area: 100000
  #     # Optional: minimum width/height of the bounding box for the detected object (default: 0)
  #     min_ratio: 0.5
  #     # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
  #     max_ratio: 2.0
  #     # Optional: minimum score for the object to initiate tracking (default: shown below)
  #     min_score: 0.5
  #     # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
  #     threshold: 0.7
      # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
      # Checks based on the bottom center of the bounding box of the object
      # mask: 0,0,1000,0,1000,200,0,200
